// Auto-generated by deploy script
// Deployed at: 2026-01-26T14:27:40.166Z

export const WORDLE_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3' as const;

export const WORDLE_ABI = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "player",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "won",
        "type": "bool"
      }
    ],
    "name": "GameEnded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "player",
        "type": "address"
      }
    ],
    "name": "GameStarted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "player",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "attempt",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bytes5",
        "name": "guess",
        "type": "bytes5"
      },
      {
        "indexed": false,
        "internalType": "enum Wordle.LetterStatus[5]",
        "name": "hints",
        "type": "uint8[5]"
      }
    ],
    "name": "GuessSubmitted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_GUESSES",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "WORD_LENGTH",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "games",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "attempts",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "gameFinished",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "won",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "player",
        "type": "address"
      }
    ],
    "name": "getGame",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "attempts",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "gameFinished",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "won",
        "type": "bool"
      },
      {
        "internalType": "bytes5[6]",
        "name": "guesses",
        "type": "bytes5[6]"
      },
      {
        "internalType": "enum Wordle.LetterStatus[5][6]",
        "name": "hints",
        "type": "uint8[5][6]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getMyGame",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "attempts",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "gameFinished",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "won",
        "type": "bool"
      },
      {
        "internalType": "bytes5[6]",
        "name": "guesses",
        "type": "bytes5[6]"
      },
      {
        "internalType": "enum Wordle.LetterStatus[5][6]",
        "name": "hints",
        "type": "uint8[5][6]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "startGame",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes5",
        "name": "guess",
        "type": "bytes5"
      }
    ],
    "name": "submitGuess",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
