const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying Wordle contract...");

  // Get signers - first one deploys, second one will be the oracle
  const [deployer, oracleSigner] = await hre.ethers.getSigners();
  const oracleAddress = await oracleSigner.getAddress();

  console.log(`Deployer: ${await deployer.getAddress()}`);
  console.log(`Oracle address: ${oracleAddress}`);

  // Get the contract factory
  const Wordle = await hre.ethers.getContractFactory("Wordle");

  // Deploy with oracle address
  const wordle = await Wordle.deploy(oracleAddress);

  // Wait for deployment to finish
  await wordle.waitForDeployment();

  const address = await wordle.getAddress();
  console.log(`Wordle deployed to: ${address}`);

  // Get the ABI from compilation artifacts
  const artifact = require("../artifacts/contracts/wordle.sol/Wordle.json");

  // Save contract info for the React frontend
  const frontendPath = path.join(__dirname, "../src/contracts/Wordle.ts");
  const frontendDir = path.dirname(frontendPath);

  if (!fs.existsSync(frontendDir)) {
    fs.mkdirSync(frontendDir, { recursive: true });
  }

  const frontendContent = `// Auto-generated by deploy script
// Deployed at: ${new Date().toISOString()}

export const WORDLE_ADDRESS = '${address}' as const;

export const WORDLE_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  fs.writeFileSync(frontendPath, frontendContent);
  console.log(`Frontend contract info saved to: src/contracts/Wordle.ts`);

  // Save oracle config
  const oracleDir = path.join(__dirname, "../oracle");
  if (!fs.existsSync(oracleDir)) {
    fs.mkdirSync(oracleDir, { recursive: true });
  }

  const oracleConfig = {
    contractAddress: address,
    // Hardhat account #1 private key (for local dev only!)
    oraclePrivateKey: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    rpcUrl: "http://127.0.0.1:8545",
    abi: artifact.abi
  };

  const oracleConfigPath = path.join(oracleDir, "config.json");
  fs.writeFileSync(oracleConfigPath, JSON.stringify(oracleConfig, null, 2));
  console.log(`Oracle config saved to: oracle/config.json`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
