const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying Wordle contract...");

  // Get the contract factory
  const Wordle = await hre.ethers.getContractFactory("Wordle");

  // Deploy (no constructor parameters needed)
  const wordle = await Wordle.deploy();

  // Wait for deployment to finish
  await wordle.waitForDeployment();

  const address = await wordle.getAddress();
  console.log(`Wordle deployed to: ${address}`);

  // Get the ABI from compilation artifacts
  const artifact = require("../artifacts/contracts/wordle.sol/Wordle.json");

  // Save contract info for the React frontend
  const outputPath = path.join(__dirname, "../src/contracts/Wordle.ts");
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileContent = `// Auto-generated by deploy script
// Deployed at: ${new Date().toISOString()}

export const WORDLE_ADDRESS = '${address}' as const;

export const WORDLE_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, fileContent);
  console.log(`Contract info saved to: src/contracts/Wordle.ts`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
