import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Deploying Greeter contract...");

  // Get the contract factory
  const Greeter = await ethers.getContractFactory("Greeter");

  // Deploy with initial greeting
  const greeter = await Greeter.deploy("Hello, Blockchain!");

  // Wait for deployment to finish
  await greeter.waitForDeployment();

  const address = await greeter.getAddress();
  console.log(`Greeter deployed to: ${address}`);

  // Get the ABI from compilation artifacts
  const artifact = require("../artifacts/contracts/Greeter.sol/Greeter.json");

  // Save contract info for the React frontend
  const contractInfo = {
    address: address,
    abi: artifact.abi,
  };

  // Write to src/contracts folder
  const outputPath = path.join(__dirname, "../src/contracts/Greeter.ts");
  const outputDir = path.dirname(outputPath);

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileContent = `// Auto-generated by deploy script
// Deployed at: ${new Date().toISOString()}

export const GREETER_ADDRESS = '${address}' as const;

export const GREETER_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  fs.writeFileSync(outputPath, fileContent);
  console.log(`✅ Contract info saved to: src/contracts/Greeter.ts`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
